package com.example.toan;

public enum ApplianceType {
    GENERAL_LIGHTING,
    SWITCH,
    BLOOD_PRESSURE_METER,
    BODY_WEIGHING_MACHINE,
    CHINICAL_THERMOMETER,
    HOME_AIRCONDITIONER,
    UNKNOWN
}
